# Custom common properties
app.log.project-name=ratelimiter

# Standard Spring logging configuration
logging.file.path=logs
logging.file.name=ratelimiter.log
ratelimiter.config.path = classpath:rules.yml
ratelimiter.storage.type = caffeine
spring.profiles.active=dev

server.port=8080
server.tomcat.max-connections=65000
server.tomcat.accept-count=15000
server.tomcat.threads.max=4000